# Generated by Django 4.0.4 on 2022-05-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.TextField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
