# Generated by Django 4.0.4 on 2022-05-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
