# Generated by Django 4.0.4 on 2022-05-02 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
        ('ticketsystem', '0003_ticket_seat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_event',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='QR_Code',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_owner',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('QR_Code', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsystem.ticket')),
            ],
        ),
    ]
