# Generated by Django 4.0.4 on 2022-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsystem', '0004_rename_ticket_event_ticket_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(default='normal', max_length=10),
            preserve_default=False,
        ),
    ]
