# Generated by Django 4.0.4 on 2022-05-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
        ('ticketsystem', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('QR_Code', models.TextField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='authentication.user')),
                ('payment_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_event', to='ticketsystem.event')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticketsystem.ticket', unique=True)),
            ],
        ),
    ]
